name: Docker Image CI

on:
  push:
    tags:
          - 'v*'  # Matches any version tag starting with 'v'

jobs:

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "IMAGE_NAME=rabbitmq" >> $GITHUB_ENV
        echo "TAG=$(echo ${{ github.ref }} | sed -n 's/refs\/tags\/v//p')" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image and push to GitHub Container Registry
      shell: bash
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ env.REPO_NAME }}:${{ env.IMAGE_NAME }}_${{ env.TAG }}
        docker images
        docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.IMAGE_NAME }}_${{ env.TAG }}
