name: Deploy Docker Image

# MIT License

# Copyright (c) 2024 Derson Productions, LLC

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# 1. The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# 2. The name "Derson Productions" and any associated trademarks or other identifiers
# may not be used to endorse or promote products derived from this Software without
# specific prior written permission from Derson Productions, LLC.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Tag for the Docker image'
          required: true
          default: 'v1.0.0'
  push:
    tags:
          - 'v*'  # Matches any version tag starting with 'v'

jobs:      
  scan_and_lint:
    name: Scan and Lint Docker Image
    uses: ./.github/workflows/image-linter-and-security-scan.yml

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [
        scan_and_lint
      ]
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4.2.0
      # https://github.com/actions/checkout
      with:  
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        ssh-strict: true
        ssh-user: git
        persist-credentials: false
        fetch-depth: 1
        fetch-tags: true
        show-progress: true
        github-server-url: https://github.com
    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        # if env.tag is defined, use it, otherwise use the tag from the event
        if [ -z "${{ inputs.tag }}" ]; then
          echo "TAG=$(echo ${{ github.ref }} | sed -n 's/refs\/tags\/v//p')" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
        fi
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1
      # https://github.com/docker/setup-buildx-action
      with:
          buildkitd-flags: --debug

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
      shell: bash
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}
        docker images

    - name: Build the Docker image and push to GitHub Container Registry
      shell: bash
      run: |
        docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}
