name: Docker Image CI

on:
  push:
    tags:
          - 'v*'  # Matches any version tag starting with 'v'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "IMAGE_NAME=rabbitmq" >> $GITHUB_ENV
        echo "TAG=$(echo ${{ github.ref }} | sed -n 's/refs\/tags\/v//p')" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      # Get latest tag from the repository
    - name: Get the latest tag and export to environment
      id: get_tag
      shell: bash
      run: 
    - uses: actions/checkout@v4
    - name: Build the Docker image and push to GitHub Container Registry
      shell: bash
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }} ghcr.io/${{ github.repository }}:${{ env.TAG }}
